- name: Printing #we can give anything
  hosts: local #if local ip
  connection: local #no need of creds, ansible will handly ansible server
  vars_files:
  - information.yaml   #take info from this file
  tasks:
  - name: printing the information #our wish
    ansible.builtin.debug:  #module for printing
      msg: "hi {{Fullname}}, I am from {{Place}}, currently i am doing {{occupation}}" #msg which we want to print
  - name: printing different
    vars:
      Fullname: deepthi
    ansible.builtin.debug:
      msg: "hi {{Fullname}}, I am from {{Place}}, currently i am doing {{occupation}}"