- name: loop concept
  hosts: web
  become: yes
  tasks:
  - name: "installing package"
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
      - { name: "gcc", state: "present" }
      - { name: "mysql", state: "present" }
      - { name: "nginx", state: "present" }  